### ISSUE TITLE
Faction mixup on wall reports

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#101]
Bug report from _malibukenny [2194067]_

**Comment by Kivou-2000607** [comment]
It comes from the script. Even json/csv export swap members => @Helcostr

**Comment by Helcostr** [comment]
thanks

**Comment by Helcostr** [comment]
Thanks. I have submitted a bug report.

https://www.torn.com/forums.php#/p=threads&f=19&t=16120281&b=0&a=0

**Comment by Helcostr** [comment]
This issue is now resolved https://www.torn.com/forums.php#/p=threads&f=67&t=16085532&b=0&a=0&start=20&to=19686386

**Comment by Kivou-2000607** [comment]
thanks
