### ISSUE TITLE
Import walls while flying

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#102]
Seems to be impossible (no response from the script).
Maybe html changes.
To be investigated...
@Helcostr

**Comment by Helcostr** [comment]
Can i get a link?

**Comment by Kivou-2000607** [comment]
No sure I can do that... since I guess the html changes if you're flying or not.
It's just speculation didn't have time to investigate

**Comment by Helcostr** [comment]
Looks the same to me.

**Comment by Kivou-2000607** [comment]
Script, v3.2.0
