### ISSUE TITLE
Turn off Bonus Hits consideration for Average Respect

### ISSUE THREAD

**Issue by Helcostr** [Kivou-2000607/yata#111]
the_hoff: we have a player that wants to award the top performers by average respect but remove the bonus hits
Helcostr: oh that's a custom program i wrote on my private site
Helcostr: #slow development :3
Helcostr: u can use yata for this
Helcostr: but u will have to use ur brain as well XD
Helcostr: basically take their total respect, subtract bonus hit respect, divide by total number of hits minus the amount of bonus hits
Helcostr: oh wait
Helcostr: use yata and a spreadsheet*

**Comment by Helcostr** [comment]
(I have no idea how to add lables)

**Comment by Kivou-2000607** [comment]
That's what all reports do
