### ISSUE TITLE
Live chain report influenced by report generation of older chain.

### ISSUE THREAD

**Issue by kib** [Kivou-2000607/yata#154]
When watching a live chain report, I noticed that there were two previous chains for which there was no report generated.

When I clicked the 'generate report' button and went back to my live report I noticed it had started to become messed up - displaying data from one of the reports currently generated.

Specifically it was showing the correct number of hits at the top, but the histogram at the bottom was from a previous chain with more hits and different participants.

It also showed up wrong in the report overview, with a current live chain having only a start date (correct) and the same number of hits and total respect as a previous chain (incorrect)

**Comment by kib** [comment]
![image](https://user-images.githubusercontent.com/2970526/68280681-50cd6380-0076-11ea-90f4-e681c06def97.png)

**Comment by Kivou-2000607** [comment]
mmm first time I hear that... I'll have a look. Seems very bad.

**Comment by Kivou-2000607** [comment]
Added 1 more sanity check: 1f0311fe79d3d4fd7ebbe3250416b616d9d6d972
