### ISSUE TITLE
'Silicon Valley' honor: info popup not formatted

### ISSUE THREAD

**Issue by kib** [Kivou-2000607/yata#155]
It's only minor but I just happen to notice:

![image](https://user-images.githubusercontent.com/2970526/68281020-07c9df00-0077-11ea-8ee8-f4d51258d68c.png)

**Comment by Kivou-2000607** [comment]
That's an easier one to fix ^^

**Comment by Kivou-2000607** [comment]
3ada7abf664d2767dde566efd440e3898a43ffa4
