### ISSUE TITLE
faction tree

### ISSUE THREAD

**Issue by kwartz-2002288** [Kivou-2000607/yata#16]
No more working since the possibility of changing background.

**Comment by Kivou-2000607** [comment]
What do you mean by not working ?

**Comment by kwartz-2002288** [comment]
The modifications done in YATA/tree are no more repercuted in the faction pages since your background upgrade.

**Comment by Kivou-2000607** [comment]
it's a cache problem, your browser is not reloading the image on the faction page.
On yata it is reloading because I'm displaying `image.png?cache=randomnumber` so the browser doesn't consider it as the same image.
