### ISSUE TITLE
add a dashboard showing current active chain counts

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#170]
Created by Daystar [2048164]

**Comment by Kivou-2000607** [comment]
I don't understand what it means

**Comment by boomgoesthedynamite** [comment]
What I was thinking of is kind of expanding the chrontab report.  That currently shows what factions are running live reports.  It would be cool if there was a way to see what their hit count was on that page.
(Daystar)

**Comment by Jamm8** [comment]
It would be useful if the timeout time on the live chain report counted down. Its just a static number right now. Could also have the timeout at the top under faction counting down like the NPC timer, perhaps with the count as well.

**Comment by Kivou-2000607** [comment]
@Daystar: it would mean sharing private data so I don't think I'll do it
@Jamm8 : It used to be updated but at the end, the amount of requests to the website was insane compared to, I guess, the times it was actually seen. I'll suggest you try the chain watching function of the YATA bot, it's more appropriate.

Closing this requests. We can talk more about it on the discord. Thanks for the suggestions.
