### ISSUE TITLE
Order Target list by Notes

### ISSUE THREAD

**Issue by Jamm8** [Kivou-2000607/yata#180]
Selecting to order the targets list by Notes does not change the order of this list. 

On Opera GX (Chomium-based)

**Comment by Kivou-2000607** [comment]
You mean the ordering is wrong? Or that it does nothing.
Maybe try to refresh to page before sorting, if you modified a note in between it will not be considered by the sorter.

**Comment by Jamm8** [comment]
I did a ctrl f5 reload. The order does change when you first sort it by note so it is ordering it by something, but it doesn't seem to be alphabetically by the note. 

![before](https://user-images.githubusercontent.com/10996162/70332283-36221200-180f-11ea-82fc-dc56a9802194.png)
![after](https://user-images.githubusercontent.com/10996162/70332290-37ebd580-180f-11ea-9d48-8f291a531035.png)

**Comment by Kivou-2000607** [comment]
indeed, I'll have a look thanks

**Comment by Jamm8** [comment]
Do you need to extract the value from the input?

https://mottie.github.io/tablesorter/docs/example-option-text-extraction.html

**Comment by Kivou-2000607** [comment]
Man you made my day!
Didn't know this feature.
Works better now?

1050d954217d1e3734acc5f1af98426e8a9b6375

**Comment by Jamm8** [comment]
Works perfectly now. 
Great job on the site btw. It's so useful. 
Thanks for all the work.
