### ISSUE TITLE
Red 100% markers for completed networth awards

### ISSUE THREAD

**Issue by kib** [Kivou-2000607/yata#23]
It also does not hide them when 'Hide Achieved Awards' is active, i.e. it always shows them in both views.

![](https://i.imgur.com/cdn5JUm.png)

In this view the networth is 350 M, but the 100k award is showing as non-complete 100%

**Comment by Kivou-2000607** [comment]
I made a modification no long ago to take into account the time needed before having this award... I guess I messed up somewhere...

**Comment by Kivou-2000607** [comment]
that was a typo...
6ac036c5bc4dd88ac9cc7ebb298a9d6fbbf3469e
044f8e6090c2e420fee13aa6f76a04fa79703633
