### ISSUE TITLE
Show personal NNB in Faction Members

### ISSUE THREAD

**Issue by Marabon** [Kivou-2000607/yata#273]
Hey,

I've been looking around but unable to find some place to see my own NNB.
I noticed you can see/share it in Faction/Members though.
Would it be possible to make the values for yourself shown to you even if you haven't clicked the share icon? (Additionally possibly maybe a "profile"/landing page with personal useful stats? Not sure which those would be though except NNB)
So that it looks something like: val (icon) val2 (icon)

Thanks for a great site!

**Comment by Kivou-2000607** [comment]
Hey,
this feature will come with a proper profile section indeed.
But it needs time to develop.

At some point it'll be there.

**Comment by Marabon** [comment]
Thanks!

Would it be easier and less time consuming to simply add the values in front of the icons of your own row in faction members list in the meantime?

I could still see that as a slight improvement even in addition to a proper profile section.

**Comment by Kivou-2000607** [comment]
Yes but this value is not computed if not shared

**Comment by Marabon** [comment]
I see. Thanks for quick replies and thanks again for the work, the site/service is great!
