### ISSUE TITLE
Pinned awards: hover text shows markup code (all)

### ISSUE THREAD

**Issue by kib** [Kivou-2000607/yata#284]
Example:

In the list of awards I am hovering over the 'days to finish' for the unarmed award. It shows a hover dialog with correct markup code:

![2020-05-11 09_10_40-YATA - Awards - Brave](https://user-images.githubusercontent.com/2970526/81534093-b8d36e00-9367-11ea-80c9-86d0ef00c71d.png)

When I pin the same target to the **pinned awards** list and hover there I get a broken popup:

![Capture](https://user-images.githubusercontent.com/2970526/81534142-d0125b80-9367-11ea-91cd-011692d86ffa.PNG)

This is the case for all pinned hovers that contain markup as far as i can see.

**Comment by Kivou-2000607** [comment]
Mmmm it works fine with we. But it means that the js tooltip library is not loaded.
Is it consistent? Does it only happen after a specific set of actions?

**Comment by kib** [comment]
It happens right away, only on the pinned awards though

**Comment by kib** [comment]
Ah. I just did a force reload (ctrl-F5) and it happens right away but then after about 2 minutes or so it is corrected. I am guessing the library is loading very slowly for some reason.

**Comment by kib** [comment]
Some further testing shows that the popup is not rendered properly by the browsers I used until all elements on the page have finished loading. Until this happens I get the incorrect view as shown in screenshot. I am unsure what is causing one of the elements to load slower than the others, but I could reproduce on both Chrome and IE browsers at 2 different locations. 

As this is not a code bug I'll close the issue.
