### ISSUE TITLE
Make Awards Searchable

### ISSUE THREAD

**Issue by Fogest** [Kivou-2000607/yata#286]
Hello,

When on the awards page sometimes I want to search for an honour/award. Unfortunately when doing CTRL + F you cannot search the content in the images and thus can't CTRL + F by award name.

Would it be possible to implement a solution like you can see here: https://stackoverflow.com/questions/37366764/how-to-make-images-searchable-via-ctrlf

I see that you already have the title="Award Name" on each award image so I do not believe this is a large task to change.

I am open to making this change via a pull request if you are busy or would like help :)

**Comment by Kivou-2000607** [comment]
12ce042bda0222a6a16c16aafb64f180d81ba899
