### ISSUE TITLE
Imprecision in respect/hit

### ISSUE THREAD

**Issue by kwartz-2002288** [Kivou-2000607/yata#29]
Example in the last chain report (active atm)
Hits / Attacks: 2563 / 2712    ( 95%) | Respect earnt: 12839 | Respect / hit: 4.73
4.73 is rather Respect/attack than Respect/hit (and it's somewhat a relevant indicator too!)

In the list of chain view, we find for the same chain Respect / hi     5.01   (coherent!)

**Comment by Kivou-2000607** [comment]
7cd2a3ae67b7bfd0cda02b279dd5bab331c246ff
