### ISSUE TITLE
Item images not loading: /bazaar images (and possibly others) are returning http 503

### ISSUE THREAD

**Issue by sixsixseven** [Kivou-2000607/yata#294]
![Screen Shot 2020-06-25 at 10 17 45](https://user-images.githubusercontent.com/5016748/85652098-57c7e580-b6dc-11ea-9682-fbafa86bb8e3.png)

I've checked on Chrome, Chrome:Incognito (to check without extensions running), and Safari.

**Comment by sixsixseven** [comment]
Reading through some of the forum posts on TC it appears this is a Cloudflare problem. I'll see if I can get cached versions up to an s3 bucket that you can use.

**Comment by Kivou-2000607** [comment]
Yeah I don't think there is much I can do here

**Comment by sixsixseven** [comment]
I can try to download locally somehow, and save to an s3 bucket. I’ll work on it.

**Comment by sixsixseven** [comment]
[https://www.torn.com/forums.php#!p=threads&f=19&t=16170672&b=0&a=0](https://www.torn.com/forums.php#!p=threads&f=19&t=16170672&b=0&a=0)

Put a bug report in the TC Forums. Let's see if they fix support for this. I tried for hours to mass download the item images for caching without any luck.

**Comment by sixsixseven** [comment]
Ched disabled JS challenge for images subdirectory. Images appear to now load properly.

**Comment by Kivou-2000607** [comment]
> Ched disabled JS challenge for images subdirectory (for now). Images appear to now load properly.

Thanks for the report mate!!!

**Comment by sixsixseven** [comment]
no worries man - I like what you're building. It's in my target language using my target framework using an API on a game I use as I learn about programming. I'm not sure things could have lined up any better!
