### ISSUE TITLE
Delete Confirmation on Targets Page

### ISSUE THREAD

**Issue by varadins** [Kivou-2000607/yata#310]
Would you please consider adding a delete confirmation on the attack page to prevent inadvertant taps on the trashcan icon?  On small screens such a mobile devices, it's easy to click the trashcan in stead of the attack icon if you have fat fingers.

**Comment by Kivou-2000607** [comment]
Done! 503b341

**Comment by Kivou-2000607** [comment]
805e501

**Comment by varadins** [comment]
Add confirmation on individual items in list?
