### ISSUE TITLE
TT War Error

### ISSUE THREAD

**Issue by sixthjittoo** [Kivou-2000607/yata#319]
Kivou [2000607]
Dear sir,
i'm new here at Github. and first apologize don't know how do i report this bug. 

https://prnt.sc/u0cll7

// ==UserScript==
// @name         YATA - Walls
// @namespace    https://yata.alwaysdata.net/
// @version      1.0.1
// @icon64       data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iOTMuMTAxbW0iIGhlaWdodD0iOTMuMTAxbW0iIHZlcnNpb249IjEuMSIgdmlld0JveD0iMCAwIDkzLjEwMSA5My4xMDEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPgogPGRlZnM+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJsaW5lYXJHcmFkaWVudDg2MSIgeDE9IjQwLjQ4MSIgeDI9IjQwLjQ4MSIgeTE9IjkyLjYwNCIgeTI9Ii0uNTI5MTYiIGdyYWRpZW50VHJhbnNmb3JtPSJ0cmFuc2xhdGUoLjc3NzUxIC43Nzc1MSkiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIiBzcHJlYWRNZXRob2Q9InJlcGVhdCI+CiAgIDxzdG9wIHN0b3AtY29sb3I9IiM3NTc1NzUiIG9mZnNldD0iMCIvPgogICA8c3RvcCBzdG9wLWNvbG9yPSIjZmZmIiBvZmZzZXQ9IjEiLz4KICA8L2xpbmVhckdyYWRpZW50PgogIDxmaWx0ZXIgaWQ9ImZpbHRlcjg3MSIgeD0iLS4wMTIiIHk9Ii0uMDEyIiB3aWR0aD0iMS4wMjQiIGhlaWdodD0iMS4wMjQiIGNvbG9yLWludGVycG9sYXRpb24tZmlsdGVycz0ic1JHQiI+CiAgIDxmZUdhdXNzaWFuQmx1ciBzdGREZXZpYXRpb249IjAuNDU0NTk0MDQiLz4KICA8L2ZpbHRlcj4KIDwvZGVmcz4KIDxwYXRoIGQ9Im05Mi4wMSA0Ni41NWE0NS40NTkgNDUuNDU5IDAgMCAxLTQ1LjQ1OSA0NS40NTkgNDUuNDU5IDQ1LjQ1OSAwIDAgMS00NS40NTktNDUuNDU5IDQ1LjQ1OSA0NS40NTkgMCAwIDEgNDUuNDU5LTQ1LjQ1OSA0NS40NTkgNDUuNDU5IDAgMCAxIDQ1LjQ1OSA0NS40NTl6IiBmaWxsPSJ1cmwoI2xpbmVhckdyYWRpZW50ODYxKSIgZmlsdGVyPSJ1cmwoI2ZpbHRlcjg3MSkiIHN0cm9rZT0iIzQ0N2U5YiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBzdHJva2Utd2lkdGg9IjEuODQ0MSIgc3R5bGU9InBhaW50LW9yZGVyOm1hcmtlcnMgZmlsbCBzdHJva2UiLz4KIDxnIHRyYW5zZm9ybT0ibWF0cml4KDE5LjQ3OSAwIDAgMTkuNDc5IDIzMDQuMiAtMjU0OS44KSI+CiAgPGcgdHJhbnNmb3JtPSJtYXRyaXgoLjA0NDExNyAwIDAgLjA0NDExNyAtMTEyLjQxIDEyOS42MikiPgogICA8cGF0aCBkPSJtLTc5LjE1NiA4Ni4zNTEgMTcuNTQ4LTM4Ljc1NWgxOC45OTZsLTI3LjY4MyA1NC44MjR2MzEuMTkzaC0xNy42NjR2LTMxLjE5M2wtMjcuNjgzLTU0LjgyNGgxOS4wNTR6IiBmaWxsPSIjNDQ3ZTliIiBzdHJva2U9IiM0MTRjNTEiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgc3Ryb2tlLXdpZHRoPSIzLjk0MjIiIHN0eWxlPSJwYWludC1vcmRlcjptYXJrZXJzIGZpbGwgc3Ryb2tlIi8+CiAgPC9nPgogPC9nPgogPGcgdHJhbnNmb3JtPSJtYXRyaXgoLjQ3NDIgLS44ODc2NiAuODY5NzkgLjQ4MDY0IDAgMCkiIGZpbGw9IiM0MTRjNTEiIHN0cm9rZT0iI2FkYWRhZCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBzdHJva2Utd2lkdGg9Ii42NTY2OCIgc3R5bGU9InBhaW50LW9yZGVyOm1hcmtlcnMgZmlsbCBzdHJva2UiIGFyaWEtbGFiZWw9IkFUQSI+CiAgPHBhdGggZD0ibS0yNS4yODUgOTYuMDE1aC01LjkyNDNsLTEuMTI2MyAzLjM3ODloLTMuNTkyOWw2LjEwNDUtMTYuMzk5aDMuMTMxMWw2LjEzODMgMTYuMzk5aC0zLjU5Mjl6bS01LjAxMi0yLjczNjloNC4wOTk3bC0yLjA2MTEtNi4xMzgzeiIgc3R5bGU9InBhaW50LW9yZGVyOm1hcmtlcnMgZmlsbCBzdHJva2UiLz4KICA8cGF0aCBkPSJtLTguMDA4MiA4NS43MzJoLTUuMDIzMnYxMy42NjJoLTMuMzc4OXYtMTMuNjYyaC00Ljk1NTd2LTIuNzM2OWgxMy4zNTh6IiBzdHlsZT0icGFpbnQtb3JkZXI6bWFya2VycyBmaWxsIHN0cm9rZSIvPgogIDxwYXRoIGQ9Im0xLjgzNTUgOTYuMDE1aC01LjkyNDNsLTEuMTI2MyAzLjM3ODloLTMuNTkyOWw2LjEwNDUtMTYuMzk5aDMuMTMxMWw2LjEzODMgMTYuMzk5aC0zLjU5Mjl6bS01LjAxMi0yLjczNjloNC4wOTk3bC0yLjA2MTEtNi4xMzgzeiIgc3R5bGU9InBhaW50LW9yZGVyOm1hcmtlcnMgZmlsbCBzdHJva2UiLz4KIDwvZz4KPC9zdmc+Cg==
// @description  Import faction walls to YATA
// @supportURL   https://www.torn.com/messages.php?p=compose&XID=1934501
// @updateURL    about:blank
// @author       Helcostr [1934501]
// @run-at       document-end
// @match        https://www.torn.com/war.php?step=warreport*
// @grant        GM_xmlhttpRequest
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_getResourceText
// @grant        GM_addStyle
// @connect      yata.alwaysdata.net
// @require      https://yata.alwaysdata.net/static/integration/userscripts.style.js
// @resource     YATA_CSS https://yata.alwaysdata.net/static/integration/userscripts.style.css
// ==/UserScript==
var cssTxt  = GM_getResourceText ("YATA_CSS");
GM_addStyle (cssTxt);

(function() {
  'use strict';
  if (typeof $ != "function") {
      alert("JQuery Missing. This is a critical error.");
      return;
  }

  // Startup function
  const startup = ()=>{
      //Set up buttons
      const buttonSetup = (text,cb)=>{
          let button = $('<button class="YATA-button">');
          button.text(text);
          button.click(cb);
          $("#YATA-message-buttons").append(button);
      };

      //show info box
      $(".content-title").after(infobox);
      //Set up buttons
      buttonSetup("Export To YATA", sendJSON);
      buttonSetup("API Storage", ()=>{errorKey("", true)});
  };

  // Generate Report
  const genReport = ()=>{
      let report = []; //Prepare 2D array
      let focus = $(".enemy-faction,.your-faction"); //Grab both tables

      //Clone logic for result determination
      let resText = $(".faction-war-info").find("span.t-block > .text > a").parent().text();
      let result;
      if (resText.search("failed") != -1 || resText.search("truce") != -1)
          result = false;
      else if (resText.search("claimed") != -1)
          result = true;

      //Header row
      let row = [];
      focus.first().find("div > div > div:not(.clear,.short)").each((i,e)=>{
          let focus = $(e).text();
          if (focus=="Members") {
              row.push("Position");
              row.push("Name");
              row.push("XID");
          } else
              row.push(focus);
      });
      report.push(row);

      //For Each Table (Both the att and def table)
      focus.each((i,f)=>{
          //For each Player
          $(f).find("div > ul.members-list > li").each((i,e)=>{
              let row = [];
              row.push($(f).hasClass('your-faction') == result ?"Attacker":"Defender"); //Determine if the user is att or def

              $(e).find("div:not(.clear)").each((i,e)=>{
                  let focus = $(e);

                  if (focus.hasClass("member")) {//Player info (name, xid)
                      focus = focus.find("a.name");
                      let name = focus.data("placeholder");

                      if (typeof name == "undefined") { //Parser for plaintext
                          row.push(focus.text());
                          row.push(parseInt(/XID=(\d+)/.exec(focus.attr("href"))[1]));
                      } else { //Parser for honor bar
                          let reg = /(\S+)\s\[(\d+)\]/.exec(name);
                          row.push(`="${reg[1]}"`);
                          row.push(parseInt(reg[2]));
                      }
                  } else //All other data (should be numbers)
                      row.push(parseInt(focus.text().replace(/\D/g,'')));
              });
              report.push(row);
          });
      });
      return report;
  };

  const createJSON = ()=>{
      let players = [];
      let gen = genReport();
      let head = gen.shift();
      let focus = $(".faction-war-info");
      let links = focus.find("span.t-block > .text > a");
      let lazy = "(\\d{2})-(\\d{2})-(\\d{4}) (\\d{2}):(\\d{2}):(\\d{2})";
      let ts = (new RegExp(lazy+" to "+lazy)).exec(focus.find("span.t-block:eq(1)").text().trim());
      let resText = links.parent().text();
      let result;
      if (resText.search("failed") != -1)
          result = -1;
      else if (resText.search("claimed") != -1)
          result = 1;
      else if (resText.search("truce") != -1)
          result = 0;
      let report = {
          author:parseInt(getCookie("uid")),
          id:parseInt(/(\d+)/.exec($(".title-black").text())[1]),
          att_fac:parseInt(/ID=(\d+)/.exec(links.eq(0).attr("href"))[1]),
          att_fac_name:links.eq(0).text(),
          def_fac:parseInt(/ID=(\d+)/.exec(links.eq(1).attr("href"))[1]),
          def_fac_name:links.eq(1).text(),
          result:result,
          terr:links.eq(2).text(),
          ts_start:Date.UTC(ts[3], ts[1]-1, ts[2], ts[4], ts[5], ts[6]) / 1000,
          ts_end:Date.UTC(ts[3+6], ts[1+6]-1, ts[2+6], ts[4+6], ts[5+6], ts[6+6]) / 1000,
          participants:gen.map(e=>{
              let obj = {};
              head.forEach((f,i)=>{
                  obj[f] = e[i];
              });
              return obj;
          })
      };
      return report;
  };

  // Send to server
  const sendJSON = ()=>{
      msgbox();
      let report = createJSON();
      let key = GM_getValue("key","");
      GM_xmlhttpRequest({
          method: "POST",
          url: "https://yata.alwaysdata.net/faction/walls/import/",
          data: JSON.stringify(report),
          headers: {
              "key":key
          },
          onload: resp=> {
              try {
                  let obj = JSON.parse(resp.responseText);
                  if ("message" in obj) {
                      if ("type" in obj && obj.type>0)
                          valid(obj.message);
                      else if (obj.type == -1) {
                          switch(obj.message.apiErrorCode) {
                              case 1:
                              case 2:
                              case 10:
                                  error(obj.message.apiError);
                                  break;
                              default:
                                  error(obj.message.apiError);
                          }
                      } else
                          error(obj.message);
                  } else if (obj.status == 200)
                      error("Everything seems to be ok???");
                  else
                      error("No message received from the server");
              } catch (e) {
                  error("Failed to parse response from server" + e);
              }
          },
          ontimeout: ()=>{
              error("Request has timed out");
          },
          onerror: ()=>{
              error("Unknown error has occured when trying to send the data");
          },
          onabort: ()=>{
              error("Upon sending the data, the request was canceled");
          }
      });
  };
  startup();

})();

**Comment by Kivou-2000607** [comment]
Hey sorry I didn't catch this issue.

You need API Access perm (ingame) to be able to create these reports. Ask your leaders!
