### ISSUE TITLE
error 500 on respect simulator

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#343]
Hello,
I've been trying to use the respect sim for a while, and after a looong time of never loading, if I refresh I get this message.

Mandelbrat [2380562]
https://discord.com/channels/581227228537421825/625796758164733988/758289962675208204

**Comment by JackWetson** [comment]
Resolved by patch atm no?

**Comment by Kivou-2000607** [comment]
yes... I think ^^
