### ISSUE TITLE
Getting "int() argument must be a string, a bytes-like object or a number, not 'NoneType'"  error when logging in.

### ISSUE THREAD

**Issue by LArunkumar** [Kivou-2000607/yata#371]
int() argument must be a string, a bytes-like object or a number, not 'NoneType' 
![image](https://user-images.githubusercontent.com/9913867/96833495-2844a200-145e-11eb-8fae-0108d0e78944.png)

On Firefox/MacOS

**Comment by Kivou-2000607** [comment]
a3c9a46
