### ISSUE TITLE
Reports: multiple calls / minutes

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#377]
Apparently now API cache is based on API key for the faction section. Which means we can loop over the keys to increase the number of calls / minutes.

Kivou [2000607]
https://discord.com/channels/581227228537421825/633434261361262602/769549675149262848

- [x] Try on chain reports
- [x] Send attacks to db by bulks (like for the armory) to speed up time @JackWetson 
- [x] Same for attacks reports
- [x] Same for revives reports
- [x] Decap check

**Comment by Kivou-2000607** [comment]
I've added the bulk manager to save attacks and Counts

**Comment by JackWetson** [comment]
@Kivou-2000607 , was there anything else you wanted checking apart from the bulkhandler?

**Comment by Kivou-2000607** [comment]
No it's good
