### ISSUE TITLE
Company suggestions

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#394]
- [x] Change ws gains display to account for P or S < 1
- [ ] Add trains in some way
- [ ] Add star evolution
- [x] Add company profit (revenue - advert - wages = profit) (logs and graph)
- [x] Breakdown the total effectiveness 
- [x] Add daily/weekly filter to the graphs
- [x] Compute weekly profit
- [x] Add employees details (last action)
- [x] Automatically Update company data when director land on page and button to force update
- [x] deal with stocks #392

**Comment by OranWeb** [comment]
Not sure if this is already on the roadmap but having calculator for stock to order daily/weekly would be godsent. 

jrm250 has an API Based solution for this and also has discord Notifications to remind you to order stocks. 

https://www.torn.com/forums.php#/p=threads&f=67&t=16139093

https://docs.google.com/spreadsheets/d/1pgnaEBSVwtOi27wc1hd0QT7SYF3mA_rOuERGWq87PVM/edit#gid=1995506930
