### ISSUE TITLE
loot header

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#397]
Loot header display stuck on All level V

Kivou [2000607]
https://discord.com/channels/581227228537421825/625796758164733988/781481064262139915

**Comment by Helcostr** [comment]
Is this a website issue, or a bot issue?

**Comment by Kivou-2000607** [comment]
website

**Comment by Kivou-2000607** [comment]
582da306c912e9d98da2bf1b76f3082a51290b3c
