### ISSUE TITLE
Add drug CD / daily refill and merits to members

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#399]
is it possible to add drug cooldown and if daily refill has been used on the faction member list?

Allo [2316070]
https://discord.com/channels/581227228537421825/633434261361262602/782293065955934208

**Comment by Helcostr** [comment]
This seems very narrow scoped. While i understand the drug CD interface, A week/month report of if a user has used a refill on a specific day makes more sense.

**Comment by Kivou-2000607** [comment]
It can be used to check the energy level of the faction during chains
