### ISSUE TITLE
wrong ketamin CD

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#404]
<@!227470975317311488> On awards tab, I'm tracking my usage of Ketamine and it says 'with an average of 70mins of cool down', I just used one on Torn and I'm pretty sure it gave me ~45 minutes of cool down

Blasted [1934909]
https://discord.com/channels/581227228537421825/625796758164733988/783719134637719583

**Comment by JackWetson** [comment]
Cool down: 45-60 minutes
according to wiki data
