### ISSUE TITLE
Move to new server

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#422]
- [x] Database
- [x] Domain name
- [x] Cloudfare
- [x] Website
- [x] Crons 
- [x] Crons (reports)
- [x] Bot
- [x] Redis
- [ ] Sentry (work if decap down with 0.0) #424 
- [x] Donations
- [x] Announce new domain name
- [x] Close alwaysdata
- [ ] Newspaper article

**Comment by JackWetson** [comment]
As we mentioned, moving Sentry right now doesn't make a lot of sense due to resource, but we/I should look further into making yata less dependant on it
