### ISSUE TITLE
Not displaying next Crime to do

### ISSUE THREAD

**Issue by Dan100NPO** [Kivou-2000607/yata#437]
Hello, 

I did write about this issue on Discord 3 days ago however nobody replied to me here: https://discord.com/channels/581227228537421825/625796758164733988/800512453510430720

It appears that Yata doesn't have the "Trophy Icon" next to the next Crime I should do .

https://cdn.discordapp.com/attachments/700934742190587930/799989275147632650/Screen_Shot_2021-01-17_at_12.11.42_am.png
https://cdn.discordapp.com/attachments/700934742190587930/799989327168929852/Screen_Shot_2021-01-17_at_12.11.53_am.png
https://cdn.discordapp.com/attachments/700934742190587930/799989375420071956/Screen_Shot_2021-01-17_at_12.12.04_am.png
https://cdn.discordapp.com/attachments/700934742190587930/799989431133929492/Screen_Shot_2021-01-17_at_12.12.16_am.png

My in-game name is Dan100 [2488743] along with Yata and Discord.

Thank you

**Comment by Kivou-2000607** [comment]
bf7f2c245064b46069c29d7270bf73afa951432e
