### ISSUE TITLE
Drug Cooldown Typo

### ISSUE THREAD

**Issue by Chris00223** [Kivou-2000607/yata#440]
On https://yata.yt/faction/members/, the hover text for drug cooldown for the logged in user says "durg":

`<i class="fas fa-cannabis fa-icon-inline" style="opacity:1" title="1 hrs 32 mins 59 s of durg CD"></i>`

**Comment by Kivou-2000607** [comment]
884efd6f18d00a994cc73986bd4111f4040f0e0f
