### ISSUE TITLE
Attack level doesn't correct

### ISSUE THREAD

**Issue by rockrong** [Kivou-2000607/yata#445]
As title.
When I check my attack history by YATA, the target's level doesn't show correctly.
If I attack and leave, the level will be 1 lower than the right one.
If I mug somebody, the level will show correctly.
There are two lines and I attack the same non-active player.
[https://i.imgur.com/91sAMbY.png](https://i.imgur.com/91sAMbY.png)

**Comment by Kivou-2000607** [comment]
I don't have the level information from the attack so I compute it from the respect. With the rounding of the log it can be +-1 off.
If you add it as a target then you'll have the correct level.
