### ISSUE TITLE
typo in player stats page

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#464]
https://yata.yt/player/stats spelling error "Unkown"

Valaskjalf [1503919]
https://discord.com/channels/581227228537421825/833799320964694036/834121070348075039

**Comment by OranWeb** [comment]
https://github.com/Kivou-2000607/yata/search?q=unkown

not sure if intentional, but there's a few unkown's everywhere.

**Comment by jgonyea** [comment]
https://github.com/Kivou-2000607/yata/pull/467
