### ISSUE TITLE
change API method for getting faction roles in bot dashboard

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#479]
when I coded that the position list was not implemented in that API. I had to go through the member list. hence the current issue.

Kivou [2000607]
https://discord.com/channels/581227228537421825/884383444950466571/885194773751816193

**Comment by JackWetson** [comment]
https://github.com/Kivou-2000607/yata/blob/72656bf9fb322f0188979291a656277a14271f13/bot/views.py
it's the link just above. line 228 is the API call and 232 the loop over the members that need to be changed
