### ISSUE TITLE
Wrong Rank

### ISSUE THREAD

**Issue by drapodi** [Kivou-2000607/yata#59]
First, I LOVE your website. Second, I found a bug in how the rank is calculated in the chain live report. I am currently in a chain and while the website says I have the highest number of hits done, it says my rank is lower. Do note that my current "attacks" made are lower to that of the other person though. When hovering over rank, it says it is calculated by number of hits so it may be that it's just a typo there. 

https://ibb.co/sPmqG84

**Comment by Kivou-2000607** [comment]
Hooo thanks for the bug report...
I guess compute the rank server side based on #attacks and dynamically order user-side based on #hits.

I'll fix it asap.

**Comment by Kivou-2000607** [comment]
53fac2f2329c244fbfce0730321efdac1c584894

**Comment by Kivou-2000607** [comment]
Not sure of what I did, can you tell me if it's fix on your side?

**Comment by drapodi** [comment]
The number of hits changed since it is an ongoing chain, but they are now correctly displayed. Won't know if it is indeed fixed until I reach first place in hits again lol (if it happens). I would mark it as fixed and If I see something wrong I'll be sure to notify you. Thanks!

**Comment by drapodi** [comment]
Update! The issue still persists. The problem, if I had to guess, is not in the sorting of the list itself since it does that well but rather the assignment of the rank number. It should be (in my opinion) so that it first assigns ranks based on hits and only if its the same number then it uses another value of your choice to assign a rank number. 

https://ibb.co/ZTJKm49
^proof image

**Comment by Kivou-2000607** [comment]
Yes I agree this is what it should be doing... Sort by hit then by respect. 
Sorting is done server side, rank is computed on the fly and there is a second layer of sorting clientsside... which can explain the difference...I'll have a second look with a fake example to see what's going on.

**Comment by Kivou-2000607** [comment]
Ok, it should be fixed now.
The problem came from the bonus hit.

fix here: 6b4b813a63e98540b7ded7e64f68c9e30a363962
