### ISSUE TITLE
Wall reports

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#84]
The idea is to have an integration with a client script that parse the html and pushes a `POST` request to yata

- [x] client script for export
- [x] client script -> POST request
- [x] YATA post process and database
- [x] YATA handle POST request
- [x] YATA wall tab in faction section

see script from: https://www.torn.com/forums.php#/p=threads&f=67&t=16085532&b=0&a=0

**Comment by Echoblast53** [comment]
:wave:

**Comment by Helcostr** [comment]
Timeout results are suppose to be Truce results.
Loss results are also known as Timeout results. But we can leave them as losses.

**Comment by Kivou-2000607** [comment]
3a7da7c3f2ada2e8514f0c7d7f98dcc1822d4d55
