### ISSUE TITLE
convert everything to days

### ISSUE THREAD

**Issue by Kivou-2000607** [Kivou-2000607/yata#96]
- [x] Energy Needed -> convert with 10minutes / 5e
- [x] Hours of CD -> days left... pretty easy
- [x] Assault left -> for defends can bring it back to days with a average from day 1
- [x] For respect -> Energy needed can be converted in days like above. Or average of respects / days from day 1.
- [x] Remove tokens
- [x] bailout

- [x] change column  name comment -> days left
- [x] use floats for days left
- [x] align left tooltips

**Comment by Helcostr** [comment]
How are you storing timestamps? :)

**Comment by Kivou-2000607** [comment]
> How are you storing timestamps? :)

integers ^^

**Comment by Kivou-2000607** [comment]
https://github.com/Kivou-2000607/yata/commit/a164ae9b0c2d418094c1f101dd1d41458cad8122
